export type GameScene = {
  id: string;
  chapterId: string;
  sceneLabel?: string;
  backgroundImage?: string;
  backgroundColor?: string;
  characterName: string;
  characterAvatar?: string;
  dialogue: string;
  nextSceneId?: string;
  autoAdvanceMs?: number;
  showDialogueUI?: boolean;
  autoOpenCharacterIntro?: boolean;
  advanceAfterCharacterIntro?: boolean;
  showDialogAvatar?: boolean;
  showCharacterName?: boolean;
  dialogAvatarFrameIndex?: number;
  dialogAvatarSpriteId?: "mai" | "mai-beigo" | "bai" | "beigo" | "clock";
  dialogAvatarMotionId?:
    | "slide-in-left"
    | "sway-horizontal"
    | "pop-scale"
    | "nod-down"
    | "tremble"
    | "alarm-ring"
    | "jump-once"
    | "fall-left-recover";
  dialogAvatarMotionLoop?: boolean;
  nextSceneTransition?: {
    preset: "fade-black" | "next-day";
    durationMs?: number;
  };
};

export const GAME_SCENES: Record<string, GameScene> = {
  "scene-1": {
    id: "scene-1",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/背景/房間_關燈.jpg",
    backgroundColor: "#D6D4B9",
    characterName: "",
    dialogue: "鈴鈴鈴——",
    showDialogAvatar: true,
    showCharacterName: false,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "clock",
    dialogAvatarMotionId: "alarm-ring",
    dialogAvatarMotionLoop: true,
    nextSceneId: "scene-2",
  },
  "scene-2": {
    id: "scene-2",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "唔——已經這個時間啦？",
    showDialogAvatar: true,
    nextSceneId: "scene-3",
  },
  "scene-3": {
    id: "scene-3",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "剛出社會兩年的職場新鮮人\n平時省吃儉用，但看到喜歡的東西還是會手滑的平凡女孩",
    autoOpenCharacterIntro: true,
    advanceAfterCharacterIntro: true,
    showDialogAvatar: false,
    nextSceneId: "scene-4",
  },
  "scene-4": {
    id: "scene-4",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "該起床準備上班了。",
    showDialogAvatar: true,
    nextSceneId: "scene-5",
  },
  "scene-5": {
    id: "scene-5",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好！今天就穿這個吧！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 7,
    nextSceneId: "scene-6",
  },
  "scene-6": {
    id: "scene-6",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "早餐該～吃什麼好呢？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    nextSceneId: "scene-7",
  },
  "scene-7": {
    id: "scene-7",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/背景/關門_工作中.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "哇！！！！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-8",
  },
  "scene-8": {
    id: "scene-8",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好痛……我踩到了什麼？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-9",
  },
  "scene-9": {
    id: "scene-9",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "吼！小白怎麼又把東西扔得到處都是了！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 7,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-10",
  },
  "scene-10": {
    id: "scene-10",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "如果踩到跌倒受傷怎麼辦？這次一定要好好唸一唸她！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-11",
  },
  "scene-11": {
    id: "scene-11",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "小白～妳在嗎？我進來囉——",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 7,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-12",
  },
  "scene-12": {
    id: "scene-12",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "小麥，早呀……怎麼啦？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-13",
  },
  "scene-13": {
    id: "scene-13",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "小麥的現任室友兼大學好友\n自由接案的動畫師，時常燃燒生命趕稿",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-14",
  },
  "scene-14": {
    id: "scene-14",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "妳還問我！這個模型是妳的吧？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-15",
  },
  "scene-15": {
    id: "scene-15",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "是我的沒錯……它怎麼啦？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 1,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-16",
  },
  "scene-16": {
    id: "scene-16",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "我剛剛踩到它，差點跌死！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-17",
  },
  "scene-17": {
    id: "scene-17",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "不是跟妳說過很多次，公共空間不要亂扔東西嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 11,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-18",
  },
  "scene-18": {
    id: "scene-18",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "哎呦……我又不是故意的……",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 1,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-19",
  },
  "scene-19": {
    id: "scene-19",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "不是故意不故意的問題！是妳明明答應過我不會再這樣……",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-20",
  },
  "scene-20": {
    id: "scene-20",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "對不起，我知道了啦……",
    showDialogAvatar: true,
    showCharacterName: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-21",
  },
  "scene-21": {
    id: "scene-21",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "下不為例了喔！我先去上班了",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 13,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-22",
  },
  "scene-21-work": {
    id: "scene-21-work",
    chapterId: "ch01",
    sceneLabel: "上班",
    backgroundImage: "/images/背景/公司_白天.jpg",
    backgroundColor: "#8E8E8E",
    characterName: "小麥",
    dialogue: "",
    showDialogueUI: false,
    nextSceneId: "scene-22",
  },
  "scene-22": {
    id: "scene-22",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "咦？這個是……",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 10,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-23",
  },
  "scene-23": {
    id: "scene-23",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "這不是我們約好一起寫、重要的日記嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 10,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-24",
  },
  "scene-24": {
    id: "scene-24",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "嗯？什麼東西？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-25",
  },
  "scene-25": {
    id: "scene-25",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "……",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 10,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-26",
  },
  "scene-26": {
    id: "scene-26",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "我看小白妳……根本就不在乎別人的感受吧？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-27",
  },
  "scene-27": {
    id: "scene-27",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "欸？啊！不是的！我、我只是……",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 1,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-28",
  },
  "scene-28": {
    id: "scene-28",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "算了！我看從頭到尾，都只有我一個人在乎！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-29",
  },
  "scene-29": {
    id: "scene-29",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "早知道就不要當什麼室友了！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-30",
  },
  "scene-30": {
    id: "scene-30",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "碰！",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-31",
  },
  "scene-31": {
    id: "scene-31",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "小、小麥……？",
    showDialogAvatar: true,
    showCharacterName: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-32",
    nextSceneTransition: {
      preset: "next-day",
      durationMs: 980,
    },
  },
  "scene-32": {
    id: "scene-32",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "???",
    dialogue: "嗷...嗚",
    showDialogAvatar: false,
    nextSceneId: "scene-33",
  },
  "scene-33": {
    id: "scene-33",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "鬧鐘也還沒醒，是什麼聲音，太早了吧",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 13,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-34",
  },
  "scene-34": {
    id: "scene-34",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "不是錯覺吧，真的有聲音...",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-35",
  },
  "scene-35": {
    id: "scene-35",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "我們去捷運站 ～嗷",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-36",
  },
  "scene-36": {
    id: "scene-36",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "捷運站？這麼早，等等你會說話",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-37",
  },
  "scene-37": {
    id: "scene-37",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "對！我是小貝狗，我們快去捷運站！有小日獸在那",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 1,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-38",
  },
  "scene-38": {
    id: "scene-38",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue:
      "小貝狗？好像是小白很常提到的角色。或許可以先跟著牠去捷運站，不然感覺一時半刻，也會纏著我...",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-39",
  },
  "scene-39": {
    id: "scene-39",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "小日獸？捷運站？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-40",
  },
  "scene-40": {
    id: "scene-40",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "對！感覺到有小日獸出現在捷運站！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-41",
  },
  "scene-41": {
    id: "scene-41",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好，那我們出發吧",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-offwork",
  },
  "scene-42": {
    id: "scene-42",
    chapterId: "ch02",
    sceneLabel: "家門口",
    backgroundImage: "/images/背景/家門口巷弄_夜晚.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "所以你說小日獸是小白在日記上畫出來的角色",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-43",
  },
  "scene-43": {
    id: "scene-43",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/背景/家門口巷弄_夜晚.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷～",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-44",
  },
  "scene-44": {
    id: "scene-44",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/背景/家門口巷弄_夜晚.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "看來小白的昏迷和日記內容部件事有關係的",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-45",
  },
  "scene-45": {
    id: "scene-45",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/背景/家門口巷弄_夜晚.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "等等到家，來看看日記，雖不定有什麼線索",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-46",
    nextSceneTransition: {
      preset: "fade-black",
      durationMs: 420,
    },
  },
  "scene-46": {
    id: "scene-46",
    chapterId: "ch02",
    sceneLabel: "晚上客廳",
    backgroundImage: "/images/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "打開日記本來看看",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
  },
  "scene-morning-hub": {
    id: "scene-morning-hub",
    chapterId: "ch02",
    sceneLabel: "早晨",
    backgroundImage: "/images/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "時間差不多了",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "mai",
  },
  "scene-offwork": {
    id: "scene-offwork",
    chapterId: "ch02",
    sceneLabel: "下班",
    backgroundImage: "/images/背景/公司_黃昏.jpg",
    backgroundColor: "#8E8E8E",
    characterName: "小麥",
    dialogue: "",
    showDialogueUI: false,
  },
};

export const SCENE_ORDER = [
  "scene-1",
  "scene-2",
  "scene-3",
  "scene-4",
  "scene-5",
  "scene-6",
  "scene-7",
  "scene-8",
  "scene-9",
  "scene-10",
  "scene-11",
  "scene-12",
  "scene-13",
  "scene-14",
  "scene-15",
  "scene-16",
  "scene-17",
  "scene-18",
  "scene-19",
  "scene-20",
  "scene-21",
  "scene-21-work",
  "scene-22",
  "scene-23",
  "scene-24",
  "scene-25",
  "scene-26",
  "scene-27",
  "scene-28",
  "scene-29",
  "scene-30",
  "scene-31",
  "scene-32",
  "scene-33",
  "scene-34",
  "scene-35",
  "scene-36",
  "scene-37",
  "scene-38",
  "scene-39",
  "scene-40",
  "scene-41",
  "scene-42",
  "scene-43",
  "scene-44",
  "scene-45",
  "scene-46",
  "scene-morning-hub",
  "scene-offwork",
] as const;

export function getScenesByChapter(chapterId: string): GameScene[] {
  return SCENE_ORDER.map((id) => GAME_SCENES[id]).filter((scene) => scene.chapterId === chapterId);
}

export function getChapterScenesUntilScene(scene: GameScene): GameScene[] {
  const chapterScenes = getScenesByChapter(scene.chapterId);
  const currentIndex = chapterScenes.findIndex((item) => item.id === scene.id);
  if (currentIndex < 0) return [];
  return chapterScenes.slice(0, currentIndex + 1);
}

export const FIRST_SCENE_ID = "scene-1";
export const OFFWORK_SCENE_ID = "scene-offwork";
export const AFTER_REWARD_SCENE_ID = "scene-42";
