import type { NarrativeModeSettings } from "@/lib/game/narrativeMode";

export type StoryComicImageId =
  | "freshen"
  | "puppet"
  | "book"
  | "diaryInBag"
  | "throwBook"
  | "alarmRinging"
  | "diaryThrownOnFloor"
  | "diarySmashedOnWall"
  | "diaryDroppedOnGround"
  | "doorClose"
  | "mysteryCreatureFlash"
  | "mysteryCreatureFlashBaiRoom"
  | "beigoJumpBed"
  | "beigoBag01"
  | "beigoBag02"
  | "beigoBag03"
  | "comicCamera"
  | "diaryDemo";

export type StoryComicOverlay = {
  imageId: StoryComicImageId;
  alt: string;
  top: string;
  left?: string;
  right?: string;
  width: string;
  height?: string;
  maxWidth?: string;
  zIndex?: number;
  enterFrom?: "left" | "right" | "bottom" | "none";
  enterDelayMs?: number;
  enterDurationMs?: number;
  finalImageId?: StoryComicImageId;
  finalDelayAfterEnterMs?: number;
  finalFadeDurationMs?: number;
};

export type StorySingleComicPanel = {
  imageId: StoryComicImageId;
  alt: string;
  top: string;
  left?: string;
  right?: string;
  width: string;
  height?: string;
  maxWidth?: string;
  zIndex?: number;
  centered?: boolean;
};

export type DoorSwipeInteraction = {
  openImage: string;
  instruction?: string;
  promptDelayMs?: number;
  advanceDelayMs?: number;
};

export type GameScene = {
  id: string;
  chapterId: string;
  sceneLabel?: string;
  scenePresentation?: "default" | "outfit-reveal";
  backgroundImage?: string;
  backgroundColor?: string;
  characterName: string;
  characterAvatar?: string;
  dialogue: string;
  dialogueItalicPrefix?: string;
  nextSceneId?: string;
  autoAdvanceMs?: number;
  showDialogueUI?: boolean;
  autoOpenCharacterIntro?: boolean;
  advanceAfterCharacterIntro?: boolean;
  showDialogAvatar?: boolean;
  showCharacterName?: boolean;
  isInnerThought?: boolean;
  narrativeMode?: NarrativeModeSettings;
  dialogAvatarFrameIndex?: number;
  dialogAvatarSpriteId?: "mai" | "mai-beigo" | "bai" | "beigo" | "clock";
  dialogAvatarMotionId?:
    | "slide-in-left"
    | "fade-out-left"
    | "sway-horizontal"
    | "pop-scale"
    | "nod-down"
    | "tremble"
    | "alarm-ring"
    | "jump-once"
    | "fall-left-recover";
  dialogAvatarMotionLoop?: boolean;
  continueExitMotionId?:
    | "slide-in-left"
    | "fade-out-left"
    | "fade-out-right"
    | "sway-horizontal"
    | "pop-scale"
    | "nod-down"
    | "tremble"
    | "alarm-ring"
    | "jump-once"
    | "fall-left-recover";
  continueExitDurationMs?: number;
  nextSceneTransition?: {
    preset: "fade-black" | "next-day";
    durationMs?: number;
  };
  doorSwipeInteraction?: DoorSwipeInteraction;
  storySingleComicPanel?: StorySingleComicPanel;
  storyComicOverlays?: StoryComicOverlay[];
};

export const STORY_COMIC_OVERLAY_PRESETS = {
  ch01BeigoBagRevealFirst: [
    {
      imageId: "beigoBag01",
      alt: "蠕動的袋子",
      top: "80px",
      right: "0px",
      width: "280px",
      height: "170px",
      enterFrom: "right",
      enterDurationMs: 380,
    },
  ],
  ch01BeigoBagRevealSecond: [
    {
      imageId: "beigoBag01",
      alt: "蠕動的袋子",
      top: "80px",
      right: "0px",
      width: "280px",
      height: "170px",
      enterFrom: "none",
    },
    {
      imageId: "beigoBag02",
      finalImageId: "beigoBag03",
      finalDelayAfterEnterMs: 400,
      finalFadeDurationMs: 260,
      alt: "從袋子裡探頭出來的小貝狗",
      top: "280px",
      left: "0px",
      width: "280px",
      height: "170px",
      enterFrom: "left",
      enterDelayMs: 140,
      enterDurationMs: 380,
      zIndex: 8,
    },
  ],
} satisfies Record<string, StoryComicOverlay[]>;

export const GAME_SCENES: Record<string, GameScene> = {
  "scene-1": {
    id: "scene-1",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/428出圖/背景/房間_關燈.jpg",
    backgroundColor: "#D6D4B9",
    characterName: "",
    dialogue: "下著小雨的週一清晨",
    dialogueItalicPrefix: "下著小雨的週一清晨",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-1a",
  },
  "scene-1a": {
    id: "scene-1a",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/428出圖/背景/房間_關燈.jpg",
    backgroundColor: "#D6D4B9",
    characterName: "",
    dialogue: "鈴鈴鈴——",
    showDialogAvatar: true,
    showCharacterName: false,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "clock",
    dialogAvatarMotionId: "alarm-ring",
    dialogAvatarMotionLoop: true,
    storySingleComicPanel: {
      imageId: "alarmRinging",
      alt: "響了的鬧鐘漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 7,
      centered: true,
    },
    nextSceneId: "scene-2",
  },
  "scene-2": {
    id: "scene-2",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "唔——怎麼這麼快就天亮了？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 16,
    nextSceneId: "scene-2a",
  },
  "scene-2a": {
    id: "scene-2a",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "我還想再多睡會呢⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 16,
    nextSceneId: "scene-3",
  },
  "scene-3": {
    id: "scene-3",
    chapterId: "ch01",
    sceneLabel: "早晨",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "【小麥 MUGI】\n剛出社會兩年的職場新鮮人\n平時省吃儉用，但看到喜歡的東西還是會手滑的平凡女孩",
    autoOpenCharacterIntro: true,
    advanceAfterCharacterIntro: true,
    showDialogAvatar: false,
    nextSceneId: "scene-4",
  },
  "scene-4": {
    id: "scene-4",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "好吧⋯⋯該起床準備上班了⋯⋯",
    showDialogAvatar: true,
    showCharacterName: false,
    dialogAvatarFrameIndex: 16,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-4d",
  },
  "scene-4d": {
    id: "scene-4d",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯～今天該穿什麼好呢？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 16,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-5",
  },
  "scene-5": {
    id: "scene-5",
    chapterId: "ch01",
    sceneLabel: "小麥房間",
    scenePresentation: "outfit-reveal",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "決定了！今天就穿這個吧。",
    showDialogAvatar: false,
    dialogAvatarFrameIndex: 0,
    nextSceneId: "scene-6",
  },
  "scene-6": {
    id: "scene-6",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "早餐🎵 早餐🎵 我記得昨天冰箱裡還剩一點優格⋯⋯。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarMotionId: "slide-in-left",
    nextSceneId: "scene-7",
  },
  "scene-7": {
    id: "scene-7",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "哇！！！！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 13,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-8",
  },
  "scene-8": {
    id: "scene-8",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好痛喔⋯⋯我踩到了什麼？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-8a",
  },
  "scene-8a": {
    id: "scene-8a",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯？這不是小白的模型嗎？她怎麼又把東西丟得到處都是了！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 36,
    dialogAvatarSpriteId: "mai",
    storySingleComicPanel: {
      imageId: "puppet",
      alt: "掉落在地上的人偶漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 7,
      centered: true,
    },
    nextSceneId: "scene-9",
  },
  "scene-9": {
    id: "scene-9",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "明明上禮拜才好不容易逼她把搬家時的雜物收拾乾淨，沒想到才沒過多久，客廳又被她弄得一團亂了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 20,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-10",
  },
  "scene-10": {
    id: "scene-10",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "像這樣亂扔東西，害人踩到跌倒受傷怎麼辦？這次一定要好好唸一唸她！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 11,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-10a",
  },
  "scene-10a": {
    id: "scene-10a",
    chapterId: "ch01",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "她應該起床了吧？去她房間看看——",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 36,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-10b",
  },
  "scene-10b": {
    id: "scene-10b",
    chapterId: "ch01",
    sceneLabel: "小白房門",
    backgroundImage: "/images/428出圖/背景/關門_工作中.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "叩叩叩——",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-11",
  },
  "scene-11": {
    id: "scene-11",
    chapterId: "ch01",
    sceneLabel: "小白房門",
    backgroundImage: "/images/428出圖/背景/關門_工作中.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "小白，妳起床沒？我進來囉——",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 21,
    dialogAvatarSpriteId: "mai",
    doorSwipeInteraction: {
      openImage: "/images/428出圖/背景/開門_工作中.jpg",
      instruction: "往左滑開門",
      promptDelayMs: 520,
      advanceDelayMs: 620,
    },
    nextSceneId: "scene-12",
  },
  "scene-12": {
    id: "scene-12",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "小麥，早啊⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-13",
  },
  "scene-13": {
    id: "scene-13",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "【小白 SHIRO】\n小麥的現任室友兼大學好友\n自由接案的動畫師，時常燃燒生命趕稿\n※與小麥同居生活第108天※",
    autoOpenCharacterIntro: true,
    advanceAfterCharacterIntro: true,
    showDialogAvatar: false,
    nextSceneId: "scene-13a",
  },
  "scene-13a": {
    id: "scene-13a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "我不是剛起床，是還沒睡啦⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-13b",
  },
  "scene-13b": {
    id: "scene-13b",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "妳不是該出門去上班了嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-14",
  },
  "scene-14": {
    id: "scene-14",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "妳還問我！這個模型是妳的吧？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 20,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-15",
  },
  "scene-15": {
    id: "scene-15",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "對，是我的！妳在哪裡找到它的？我昨天還在找呢。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-16",
  },
  "scene-16": {
    id: "scene-16",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "在客廳！我剛剛踩到它，差點跌死！\n不是跟妳說過很多次，公用空間不要亂扔東西嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 21,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-18",
  },
  "scene-18": {
    id: "scene-18",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "哎呦，我又不是故意的⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-19",
  },
  "scene-19": {
    id: "scene-19",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "不是故意不故意的問題，是妳明明答應過我不會再這樣的。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 20,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-20",
  },
  "scene-20": {
    id: "scene-20",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "對不起⋯⋯",
    showDialogAvatar: true,
    showCharacterName: true,
    dialogAvatarFrameIndex: 10,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-21",
  },
  "scene-21": {
    id: "scene-21",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "下不為例了，知道嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21a0",
  },
  "scene-21a0": {
    id: "scene-21a0",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "知道了啦⋯⋯",
    showDialogAvatar: true,
    showCharacterName: true,
    dialogAvatarFrameIndex: 10,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-21a",
  },
  "scene-21a": {
    id: "scene-21a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "看小白昨晚沒睡，大概又在忙著趕稿吧？",
    showDialogAvatar: true,
    isInnerThought: true,
    dialogAvatarFrameIndex: 32,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21a2",
  },
  "scene-21a2": {
    id: "scene-21a2",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "雖然很生氣⋯⋯但這次就算了，不要對她太嚴厲好了⋯⋯",
    showDialogAvatar: true,
    isInnerThought: true,
    dialogAvatarFrameIndex: 32,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21b",
  },
  "scene-21b": {
    id: "scene-21b",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "對了，我前兩天為了妳特地去排隊買的蛋糕還在冰箱，再不吃就要壞了，妳要記得吃喔。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21c",
  },
  "scene-21c": {
    id: "scene-21c",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "嗯嗯，好啦。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-21d",
  },
  "scene-21d": {
    id: "scene-21d",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "⋯⋯怎麼一直埋頭畫畫呀？小白真的有聽到我在說什麼嗎⋯⋯",
    showDialogAvatar: true,
    isInnerThought: true,
    dialogAvatarFrameIndex: 7,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21f",
  },
  "scene-21f": {
    id: "scene-21f",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好吧，妳也不要一直工作，要找時間休息。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 7,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21f2",
  },
  "scene-21f2": {
    id: "scene-21f2",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "那就這樣，我先去上⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 7,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21f3",
  },
  "scene-21f3": {
    id: "scene-21f3",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "哇啊啊啊啊啊啊啊啊",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 13,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-21h",
  },
  "scene-21h": {
    id: "scene-21h",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "（原來是踩到小白扔在地上的素描草稿啊⋯⋯）",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-21h2",
  },
  "scene-21h2": {
    id: "scene-21h2",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "（書櫃上的書本與水培植物一併被打翻，散落在地面。植物盆內的水灑落一地，將掉落的書頁給浸溼）",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-22",
  },
  "scene-21-work": {
    id: "scene-21-work",
    chapterId: "ch01",
    sceneLabel: "上班",
    backgroundImage: "/images/428出圖/背景/公司_白天.jpg",
    backgroundColor: "#8E8E8E",
    characterName: "小麥",
    dialogue: "",
    showDialogueUI: false,
    nextSceneId: "scene-22",
  },
  "scene-22": {
    id: "scene-22",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗚哇⋯⋯我剛剛才換好的衣服都被潑濕了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-22a",
  },
  "scene-22a": {
    id: "scene-22a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "啊——！我的筆記本！！快撿起來！！！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-22b",
  },
  "scene-22b": {
    id: "scene-22b",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "筆記本⋯⋯？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 32,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-22c",
  },
  "scene-22c": {
    id: "scene-22c",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-22d",
  },
  "scene-22d": {
    id: "scene-22d",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯？這個筆記本是⋯⋯？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 32,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-23",
  },
  "scene-23": {
    id: "scene-23",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "吼呦！小麥妳怎麼會這麼不小心！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-23a",
  },
  "scene-23a": {
    id: "scene-23a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "嗚——本子都濕掉了啦！怎麼辦⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 11,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-23b",
  },
  "scene-23b": {
    id: "scene-23b",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-23c",
  },
  "scene-23c": {
    id: "scene-23c",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "可是⋯⋯我是踩到妳的東西⋯⋯才滑倒的欸⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-23d",
  },
  "scene-23d": {
    id: "scene-23d",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "搞什麼嘛⋯⋯居然是先去關心筆記本，而不是跌倒的我⋯⋯難道我比筆記本還不如嗎？",
    showDialogAvatar: true,
    isInnerThought: true,
    dialogAvatarFrameIndex: 23,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-23e",
  },
  "scene-23e": {
    id: "scene-23e",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "哎呦⋯⋯怎麼辦怎麼辦⋯⋯濕成這樣了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-26",
  },
  "scene-26": {
    id: "scene-26",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "都跌倒了，應該先關心人有沒有受傷吧？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 22,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-27",
  },
  "scene-27": {
    id: "scene-27",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "欸？啊，抱、抱歉！小麥，妳還好嗎？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-28",
  },
  "scene-28": {
    id: "scene-28",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "⋯⋯不太好，因為我的室友似乎關心一本筆記本比關心我還多⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-28a",
  },
  "scene-28a": {
    id: "scene-28a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "哪有！不是這樣的⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-29",
  },
  "scene-29": {
    id: "scene-29",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "哪不是？自從同居後，妳整天都關在房間裡畫畫⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-29a",
  },
  "scene-29a": {
    id: "scene-29a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "我叮嚀的家事妳都不處理⋯⋯買給妳的水果也都常常被放到爛掉⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-29b",
  },
  "scene-29b": {
    id: "scene-29b",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "我今天甚至因為妳跌倒了兩次，也看不出妳有多關心⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 21,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-29c",
  },
  "scene-29c": {
    id: "scene-29c",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "對不起，是我最近工作太忙⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 10,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-29d",
  },
  "scene-29d": {
    id: "scene-29d",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "算了啦。是我自己一廂情願，以為跟好朋友當室友，日子會過得更好玩，看來是我錯了⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 21,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-30",
  },
  "scene-30": {
    id: "scene-30",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "早知道一起生活會是這樣⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 21,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-31",
  },
  "scene-31": {
    id: "scene-31",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "不如不要當初不要當室友！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 11,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-31a",
  },
  "scene-31a": {
    id: "scene-31a",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "咦？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-31b",
  },
  "scene-31b": {
    id: "scene-31b",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "妳繼續工作吧！我要出門了。",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 11,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-31c",
  },
  "scene-31c": {
    id: "scene-31c",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "等、等等，妳不是真心這樣認為吧⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-31d",
  },
  "scene-31d": {
    id: "scene-31d",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "碰！",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    storySingleComicPanel: {
      imageId: "doorClose",
      alt: "關門漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 7,
      centered: true,
    },
    nextSceneId: "scene-31e",
  },
  "scene-31e": {
    id: "scene-31e",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-31f",
  },
  "scene-31f": {
    id: "scene-31f",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "小、小麥⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "bai",
    nextSceneId: "scene-31g",
    nextSceneTransition: {
      preset: "fade-black",
      durationMs: 420,
    },
  },
  "scene-31g": {
    id: "scene-31g",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "小麥她真的⋯⋯很後悔跟我當室友嗎⋯⋯",
    showDialogAvatar: true,
    isInnerThought: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "bai",
    storySingleComicPanel: {
      imageId: "book",
      alt: "筆記本漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 7,
      centered: true,
    },
    nextSceneId: "scene-31h",
  },
  "scene-31h": {
    id: "scene-31h",
    chapterId: "ch01",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小白",
    dialogue: "難道我⋯⋯是很差勁的朋友⋯⋯？",
    showDialogAvatar: true,
    isInnerThought: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "bai",
    storySingleComicPanel: {
      imageId: "book",
      alt: "筆記本漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 7,
      centered: true,
    },
    nextSceneId: "scene-32",
    nextSceneTransition: {
      preset: "fade-black",
      durationMs: 420,
    },
  },
  "scene-32": {
    id: "scene-32",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundColor: "#0B0B0F",
    characterName: "",
    dialogue: "而筆記本的邊緣，忽然透出微微的亮光⋯⋯",
    showDialogueUI: false,
    autoAdvanceMs: 2200,
    nextSceneId: "scene-33",
  },
  "scene-33": {
    id: "scene-33",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/家門口巷弄_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "天啊！已經這個時間了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-34",
  },
  "scene-34": {
    id: "scene-34",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/家門口巷弄_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "為了換下濕掉的衣服，多花了一點時間，害我上班要遲到了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 23,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-34a",
  },
  "scene-34a": {
    id: "scene-34a",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/家門口巷弄_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "沒辦法了，今天叫車去上班好了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 24,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-35",
  },
  "scene-35": {
    id: "scene-35",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundColor: "#0B0B0F",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    autoAdvanceMs: 260,
    nextSceneId: "scene-36",
  },
  "scene-36": {
    id: "scene-36",
    chapterId: "ch02",
    sceneLabel: "上班中",
    backgroundImage: "/images/428出圖/背景/公司_白天.jpg",
    backgroundColor: "#8E8E8E",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    nextSceneId: "scene-38",
  },
  "scene-37": {
    id: "scene-37",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundColor: "#0B0B0F",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    autoAdvanceMs: 260,
    nextSceneId: "scene-38",
  },
  "scene-38": {
    id: "scene-38",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "呼——終於能下班了，回家回家！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-39",
  },
  "scene-39": {
    id: "scene-39",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "是說，早上一時氣急，不小心說了太重的話⋯⋯雖然小白也有不對的地方，但我畢竟摔破了她的植物....",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-39a",
  },
  "scene-39a": {
    id: "scene-39a",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯——買個小白最愛吃的布丁回家賠罪好了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-40",
  },
  "scene-40": {
    id: "scene-40",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundImage: "/images/428出圖/背景/玄關_關燈_開門.png",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    autoAdvanceMs: 620,
    nextSceneId: "scene-41",
  },
  "scene-41": {
    id: "scene-41",
    chapterId: "ch02",
    sceneLabel: "玄關",
    backgroundImage: "/images/428出圖/背景/玄關_關燈_關門.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "我回來了——",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 6,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "slide-in-left",
    continueExitMotionId: "fade-out-right",
    continueExitDurationMs: 420,
    nextSceneId: "scene-42",
  },
  "scene-42": {
    id: "scene-42",
    chapterId: "ch02",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_關燈.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "怎麼這麼暗？平常小白聽到我回來，都會出來客廳迎接我的說⋯⋯\n難不成她還在生早上的氣？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-43",
  },
  "scene-43": {
    id: "scene-43",
    chapterId: "ch02",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "（客廳的角落裡，忽然閃出一絲黑影。）",
    showDialogAvatar: false,
    showCharacterName: false,
    storySingleComicPanel: {
      imageId: "mysteryCreatureFlash",
      alt: "一閃而過的神秘生物漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-44",
  },
  "scene-44": {
    id: "scene-44",
    chapterId: "ch02",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "呃啊！剛剛那是什麼東西？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 27,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "sway-horizontal",
    nextSceneId: "scene-45",
  },
  "scene-45": {
    id: "scene-45",
    chapterId: "ch02",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "難不成⋯⋯是有野貓闖進來了？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 28,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-45b",
  },
  "scene-45b": {
    id: "scene-45b",
    chapterId: "ch02",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "我看牠好像鑽進了小白房間⋯⋯去看看好了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 28,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-45a",
  },
  "scene-45a": {
    id: "scene-45a",
    chapterId: "ch02",
    sceneLabel: "客廳",
    backgroundImage: "/images/428出圖/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-46",
  },
  "scene-46": {
    id: "scene-46",
    chapterId: "ch02",
    sceneLabel: "小白房門",
    backgroundImage: "/images/428出圖/背景/小白房門_發光.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "小白——剛剛是不是有東西跑進妳的房間？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "slide-in-left",
    nextSceneId: "scene-46a",
  },
  "scene-46a": {
    id: "scene-46a",
    chapterId: "ch02",
    sceneLabel: "小白房門",
    backgroundImage: "/images/428出圖/背景/小白房門_發光.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "嗯？這個光是⋯⋯？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 14,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-47",
  },
  "scene-47": {
    id: "scene-47",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白１.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "嗚哇——！小、小白⋯⋯！？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 25,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "slide-in-left",
    nextSceneId: "scene-48",
  },
  "scene-48": {
    id: "scene-48",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "房間正中心，小白的雙眼緊閉、兩手抱膝，身上散發強烈的光芒，呈現漂浮於空中的狀態。",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-48a",
  },
  "scene-48a": {
    id: "scene-48a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "這、這是怎麼辦到的⋯⋯！？看起來好像真的漂浮在空中⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-48b",
  },
  "scene-48b": {
    id: "scene-48b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "小、小白！妳在表演什麼特技啦？嚇死我了！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 27,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-48c",
  },
  "scene-48c": {
    id: "scene-48c",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-48d",
  },
  "scene-48d": {
    id: "scene-48d",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "小白⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 28,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-48e",
  },
  "scene-48e": {
    id: "scene-48e",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "是因為我早上對妳兇⋯⋯妳才想嚇我的嗎？\n好啦，早上是我太過分了，我有買布丁跟妳賠罪，快下來跟我一起吃吧。",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-48f",
  },
  "scene-48f": {
    id: "scene-48f",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-49",
  },
  "scene-49": {
    id: "scene-49",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "小白？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 5,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-49a",
  },
  "scene-49a": {
    id: "scene-49a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/發光小白２.png",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-49b",
  },
  "scene-49b": {
    id: "scene-49b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "哇！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 25,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "sway-horizontal",
    storySingleComicPanel: {
      imageId: "mysteryCreatureFlashBaiRoom",
      alt: "小白房間裡一閃而過的神秘生物漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-49c",
  },
  "scene-49c": {
    id: "scene-49c",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "是、是剛剛在客廳的⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 25,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-50",
  },
  "scene-50": {
    id: "scene-50",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷嗷嗷！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-51",
  },
  "scene-51": {
    id: "scene-51",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "呃！這、這是什麼奇怪的生物！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-52",
  },
  "scene-52": {
    id: "scene-52",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷嗷嗷！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-53",
  },
  "scene-53": {
    id: "scene-53",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "這到底是怎麼了⋯⋯？奇怪的生物⋯⋯發光的小白⋯⋯難不成這一切不是特技效果！？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-53-call",
  },
  "scene-53-call": {
    id: "scene-53-call",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "小白！妳聽得到我的聲音嗎？發生什麼事了！？這個生物是什麼？妳又怎麼會變成這樣⋯⋯！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 27,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-53b",
  },
  "scene-53b": {
    id: "scene-53b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "哇——！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 25,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-54",
  },
  "scene-54": {
    id: "scene-54",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "你這奇怪的傢伙，幹麻又拍掉我想摸小白的手！？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-54a",
  },
  "scene-54a": {
    id: "scene-54a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-54b",
  },
  "scene-54b": {
    id: "scene-54b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "你、你幹嘛一直撞我啦！？再這樣下去，我要打電話報警⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-54c",
  },
  "scene-54c": {
    id: "scene-54c",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "奇怪生物不停發出嚶嚶聲，並來回在某個東西上跳耀。",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-54d",
  },
  "scene-54d": {
    id: "scene-54d",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "這、這是⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 28,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-54e",
  },
  "scene-54e": {
    id: "scene-54e",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "小白早上的筆記本⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 28,
    dialogAvatarSpriteId: "mai",
    storySingleComicPanel: {
      imageId: "book",
      alt: "筆記本漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 7,
      centered: true,
    },
    nextSceneId: "scene-55",
  },
  "scene-55": {
    id: "scene-55",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "筆記本在被翻開的瞬間，向四面八方發出強烈的光芒。",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-56",
  },
  "scene-56": {
    id: "scene-56",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "嗚啊——這個光又是⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 25,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-56-thought",
  },
  "scene-56-thought": {
    id: "scene-56-thought",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "在光芒散去後，筆記本歸為平靜，重新掉落在地上。",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-56a",
  },
  "scene-56a": {
    id: "scene-56a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "剛剛那道光⋯⋯究竟是⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-57",
  },
  "scene-57": {
    id: "scene-57",
    chapterId: "ch02",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "總、總之！要先把小白弄下來⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 20,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-58a",
  },
  "scene-57-thought": {
    id: "scene-57-thought",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-57a",
  },
  "scene-57a": {
    id: "scene-57a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "怎麼辦⋯⋯小白都沒反應⋯⋯像是陷入了昏迷一樣⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 36,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-57b",
  },
  "scene-57b": {
    id: "scene-57b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "但她的身體沒有外傷，也還有呼吸⋯⋯應該沒有立即性的危險⋯⋯嗎？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 36,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-57c",
  },
  "scene-57c": {
    id: "scene-57c",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "怎麼辦——該報警嗎？可是，這一切真是太異常了！如果小白被抓去當外星人研究怎麼辦⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-57d",
  },
  "scene-57d": {
    id: "scene-57d",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "總之，先把房間的窗簾全部拉上吧！被人看到這個異常景象就不好了⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-58",
  },
  "scene-58": {
    id: "scene-58",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "房間的窗簾在拉上後，小白身上的光成為了唯一光源。",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-58a",
  },
  "scene-58a": {
    id: "scene-58a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-59",
  },
  "scene-59": {
    id: "scene-59",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "話說回來⋯⋯你到底是什麼東西？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 22,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-59a",
  },
  "scene-59a": {
    id: "scene-59a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-59b",
  },
  "scene-59b": {
    id: "scene-59b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "唉⋯⋯看到小白又是發光又是漂浮的，你這個奇怪生物看起來似乎也不奇怪了⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 24,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-59c",
  },
  "scene-59c": {
    id: "scene-59c",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "嗯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-59d",
  },
  "scene-59d": {
    id: "scene-59d",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "牠一直在本子上跳來跳去的⋯⋯是要我看看這本筆記本嗎？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-59e",
  },
  "scene-59e": {
    id: "scene-59e",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "！這是⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 14,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60",
  },
  "scene-60": {
    id: "scene-60",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "這不是⋯⋯我和小白的交換日記本嗎⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60a",
  },
  "scene-60a": {
    id: "scene-60a",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "原來她早上擔心的本子，居然是和我的交換日記⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60b",
  },
  "scene-60b": {
    id: "scene-60b",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "不過⋯⋯裡面內容怎麼都消失了？我記得小白明明有寫日記的⋯⋯？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 35,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60c",
  },
  "scene-60c": {
    id: "scene-60c",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷！",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-60d",
  },
  "scene-60d": {
    id: "scene-60d",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "⋯⋯！這麼說來，我想起來了！！你不是小白以前自創的角色⋯⋯「小貝狗」嗎！？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60e",
  },
  "scene-60e": {
    id: "scene-60e",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷～",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-60f",
  },
  "scene-60f": {
    id: "scene-60f",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "怎麼會⋯⋯你居然出現在現實世界裡⋯⋯！？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 35,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60g",
  },
  "scene-60g": {
    id: "scene-60g",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "",
    dialogue: "小貝狗磨蹭著日記本，似乎想示意她什麼。",
    showDialogAvatar: false,
    showCharacterName: false,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    nextSceneId: "scene-60h",
  },
  "scene-60h": {
    id: "scene-60h",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "你該不會是想提示我⋯⋯這一切的發生，和小白的日記本有關吧？",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 35,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60i",
  },
  "scene-60i": {
    id: "scene-60i",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷～",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-60j",
  },
  "scene-60j": {
    id: "scene-60j",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60k",
  },
  "scene-60k": {
    id: "scene-60k",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "這一切讓我的腦袋快要不勘負荷了⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-60l",
  },
  "scene-60l": {
    id: "scene-60l",
    chapterId: "ch02",
    sceneLabel: "小白房間",
    backgroundImage: "/images/428出圖/背景/小白房間_開燈.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "不管怎樣，得先想個辦法喚醒小白⋯⋯",
    showDialogAvatar: true,
    narrativeMode: { mode: "key", visualStyle: "focus" },
    dialogAvatarFrameIndex: 3,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-61",
    nextSceneTransition: {
      preset: "next-day",
      durationMs: 980,
    },
  },
  "scene-61": {
    id: "scene-61",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundColor: "#050507",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    autoAdvanceMs: 320,
    nextSceneId: "scene-62",
  },
  "scene-62": {
    id: "scene-62",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_關燈.jpg",
    backgroundColor: "#1B1A24",
    characterName: "",
    dialogue: "鈴鈴鈴——",
    showDialogAvatar: true,
    showCharacterName: false,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "clock",
    dialogAvatarMotionId: "alarm-ring",
    dialogAvatarMotionLoop: true,
    nextSceneId: "scene-63",
  },
  "scene-63": {
    id: "scene-63",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "唔——早上啦？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 16,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-64",
  },
  "scene-64": {
    id: "scene-64",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗚啊啊啊啊！！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 29,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-64a",
  },
  "scene-64a": {
    id: "scene-64a",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-64b",
  },
  "scene-64b": {
    id: "scene-64b",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷——",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-65",
  },
  "scene-65": {
    id: "scene-65",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "你是在叫我起床嗎？原來⋯⋯這一切不是夢啊？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 30,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-66",
  },
  "scene-66": {
    id: "scene-66",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "昨天用手機查了一整個晚上，不知不覺就趴在小白床上睡著了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 31,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-66a",
  },
  "scene-66a": {
    id: "scene-66a",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "結果就算問Chat GPT，它也只會叫我去報警，真的是一點用也沒有⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 31,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-66b",
  },
  "scene-66b": {
    id: "scene-66b",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-66c",
  },
  "scene-66c": {
    id: "scene-66c",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "唉，先照常去上班好了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 31,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-66d",
  },
  "scene-66d": {
    id: "scene-66d",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷～～",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-66e",
  },
  "scene-66e": {
    id: "scene-66e",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "⋯⋯",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-66f",
  },
  "scene-66f": {
    id: "scene-66f",
    chapterId: "ch02",
    sceneLabel: "小麥房間",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "希望我回來時，一切就都恢復正常了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 31,
    dialogAvatarSpriteId: "mai",
    continueExitMotionId: "fade-out-right",
    continueExitDurationMs: 420,
    nextSceneId: "scene-67",
  },
  "scene-67": {
    id: "scene-67",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundImage: "/images/428出圖/背景/公司附近街道_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    autoAdvanceMs: 260,
    nextSceneId: "scene-68",
  },
  "scene-68": {
    id: "scene-68",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "就算發生了這麼莫名其妙的事情，社畜還是得乖乖去上班⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "slide-in-left",
    nextSceneId: "scene-68a",
  },
  "scene-68a": {
    id: "scene-68a",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_白天.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "昨天奢侈搭了計程車，今天就乖乖搭捷運吧⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 9,
    dialogAvatarSpriteId: "mai",
    continueExitMotionId: "fade-out-right",
    continueExitDurationMs: 420,
    nextSceneId: "scene-69",
  },
  "scene-69": {
    id: "scene-69",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好累喔，昨天根本沒睡好⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 24,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-70",
  },
  "scene-70": {
    id: "scene-70",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯？怎麼感覺包裡有東西在動……",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 32,
    dialogAvatarSpriteId: "mai",
    storyComicOverlays: STORY_COMIC_OVERLAY_PRESETS.ch01BeigoBagRevealFirst,
    nextSceneId: "scene-71",
  },
  "scene-71": {
    id: "scene-71",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "哇！你什麼時候偷鑽進來的！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 25,
    dialogAvatarSpriteId: "mai",
    storyComicOverlays: STORY_COMIC_OVERLAY_PRESETS.ch01BeigoBagRevealSecond,
    nextSceneId: "scene-72",
  },
  "scene-72": {
    id: "scene-72",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！「小日獸」！「小日獸」！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-73",
  },
  "scene-73": {
    id: "scene-73",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "！！！你居然會講話！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 27,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-73a",
  },
  "scene-73a": {
    id: "scene-73a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "重點是，你如果被別人看到怎麼辦？會被實驗室抓走的！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 27,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-73b",
  },
  "scene-73b": {
    id: "scene-73b",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！「小日獸」！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-74",
  },
  "scene-74": {
    id: "scene-74",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "小日⋯⋯什麼？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 28,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-74a",
  },
  "scene-74a": {
    id: "scene-74a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "（順著奇怪生物指的方向看去，小麥發現車廂裡，有隻尾巴被門夾住的黃金獵犬。）",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-75",
  },
  "scene-75": {
    id: "scene-75",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "呃！捷運上怎麼會有黃金獵犬？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-76",
  },
  "scene-76": {
    id: "scene-76",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "小日獸！小日獸！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-77",
  },
  "scene-77": {
    id: "scene-77",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "你說的小日獸⋯⋯是指牠？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-78",
  },
  "scene-78": {
    id: "scene-78",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "仔細看，他的尾巴好像被夾住了⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-78a",
  },
  "scene-78a": {
    id: "scene-78a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "怎麼車廂裡的其他乘客，都沒有注意到這個詭異的現象？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-78b",
  },
  "scene-78b": {
    id: "scene-78b",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "這麼說來⋯⋯好像也沒人注意到小貝狗的存在⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-79",
  },
  "scene-79": {
    id: "scene-79",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "⋯⋯？你是要我去幫助他嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-80",
  },
  "scene-80": {
    id: "scene-80",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "拍照！拍照！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "sway-horizontal",
    nextSceneId: "scene-81",
  },
  "scene-81": {
    id: "scene-81",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "拍照？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 33,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-82",
  },
  "scene-82": {
    id: "scene-82",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "哇啊啊啊！！！！你、你還會吐東西出來⋯⋯！？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 26,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "pop-scale",
    storySingleComicPanel: {
      imageId: "comicCamera",
      alt: "小貝狗吐出來的相機漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-83",
  },
  "scene-83": {
    id: "scene-83",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "拍照！拍照！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "sway-horizontal",
    storySingleComicPanel: {
      imageId: "comicCamera",
      alt: "小貝狗吐出來的相機漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-84",
  },
  "scene-84": {
    id: "scene-84",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "好啦好啦，別催！用這個拍就可以了是嗎？\n我看看⋯⋯應該是按這個鈕⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 21,
    dialogAvatarSpriteId: "mai",
    storySingleComicPanel: {
      imageId: "comicCamera",
      alt: "手上的相機漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-85",
  },
  "scene-85": {
    id: "scene-85",
    chapterId: "ch02",
    sceneLabel: "",
    backgroundImage: "/images/428出圖/動物事件/黃金獵犬１.png",
    backgroundColor: "#1B1A18",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    nextSceneId: "scene-86",
  },
  "scene-86": {
    id: "scene-86",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "咦？那隻黃金獵犬去哪了？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 35,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-87",
  },
  "scene-87": {
    id: "scene-87",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！日記！日記！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    storySingleComicPanel: {
      imageId: "diaryInBag",
      alt: "袋子裡露出的日記本漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-88",
  },
  "scene-88": {
    id: "scene-88",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "日記⋯⋯？啊！是指我早上隨手帶出門的小白日記本⋯⋯！？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 14,
    dialogAvatarSpriteId: "mai",
    storySingleComicPanel: {
      imageId: "diaryInBag",
      alt: "袋子裡露出的日記本漫畫格",
      top: "142px",
      width: "80%",
      maxWidth: "290px",
      zIndex: 8,
      centered: true,
    },
    nextSceneId: "scene-89",
  },
  "scene-89": {
    id: "scene-89",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "這是⋯⋯！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-90",
  },
  "scene-90": {
    id: "scene-90",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "本來消失的日記內容⋯⋯浮現了！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-90a",
  },
  "scene-90a": {
    id: "scene-90a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "這篇日記⋯⋯真的是典型的小白呢，粗心又糊裡糊塗",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 18,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-91",
  },
  "scene-91": {
    id: "scene-91",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "這隻被我吐槽後畫的黃金獵犬，我也記得。小白還幫牠取了名字，叫直太郎⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 18,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-91a",
  },
  "scene-91a": {
    id: "scene-91a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "以前交換日記時，最喜歡看她畫這些可愛小插圖了。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 18,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-92",
  },
  "scene-92": {
    id: "scene-92",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "但自從同居後，我們好像就沒再交換過日記⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 37,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-92a",
  },
  "scene-92a": {
    id: "scene-92a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-93",
  },
  "scene-93": {
    id: "scene-93",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯？你又想告訴我什麼了？仔細想想⋯⋯日記⋯⋯拍照⋯⋯捕捉黃金獵犬⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 14,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-94",
  },
  "scene-94": {
    id: "scene-94",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！小日獸！拍照！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-95",
  },
  "scene-95": {
    id: "scene-95",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "嗯⋯⋯？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 36,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-95a",
  },
  "scene-95a": {
    id: "scene-95a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "難道⋯⋯所謂的小日獸，就是小白畫的這些小動物嗎？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 38,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-96",
  },
  "scene-96": {
    id: "scene-96",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 1,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "nod-down",
    nextSceneId: "scene-96a",
  },
  "scene-96a": {
    id: "scene-96a",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "該不會⋯⋯那些消失的日記內容，都變成了小日獸！？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 38,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-96b",
  },
  "scene-96b": {
    id: "scene-96b",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷～～嗷！嗷嗷！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 1,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "nod-down",
    nextSceneId: "scene-97",
  },
  "scene-97": {
    id: "scene-97",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "",
    dialogue: "ＸＸ站到了～ＸＸ站到了～",
    showDialogAvatar: false,
    showCharacterName: false,
    nextSceneId: "scene-98",
  },
  "scene-98": {
    id: "scene-98",
    chapterId: "ch02",
    sceneLabel: "捷運",
    backgroundImage: "/images/428出圖/背景/捷運.png",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "糟糕！已經到站了！總之，晚點再來思考吧！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 34,
    dialogAvatarSpriteId: "mai",
    continueExitMotionId: "fade-out-left",
    continueExitDurationMs: 420,
    nextSceneId: "scene-98-work",
  },
  "scene-98-work": {
    id: "scene-98-work",
    chapterId: "ch02",
    sceneLabel: "上班中",
    backgroundImage: "/images/428出圖/背景/公司_白天.jpg",
    backgroundColor: "#8E8E8E",
    characterName: "",
    dialogue: "",
    showDialogueUI: false,
    nextSceneId: "scene-offwork",
  },
  "scene-99": {
    id: "scene-99",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "下班了！終於有時間來好好思考白天的事⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    dialogAvatarMotionId: "slide-in-left",
    nextSceneId: "scene-100",
  },
  "scene-100": {
    id: "scene-100",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "我記得⋯⋯昨晚在小白房間時，日記本忽然發出了光芒向外四射，然後內容變成了一片空白⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-101",
  },
  "scene-101": {
    id: "scene-101",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "如果說那些內容都變成了小日獸⋯⋯從日記本裡面逃了出來⋯⋯",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-102",
  },
  "scene-102": {
    id: "scene-102",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "那是不是只要把小日獸都抓起來，日記本就可以恢復原狀！？",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-103",
  },
  "scene-103": {
    id: "scene-103",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_黃昏.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小貝狗",
    dialogue: "嗷嗷！嗷嗷！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    dialogAvatarMotionId: "jump-once",
    nextSceneId: "scene-105",
  },
  "scene-105": {
    id: "scene-105",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/公司附近街道_夜晚.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小貝狗",
    dialogue: "嗷嗷～！",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 2,
    dialogAvatarSpriteId: "beigo",
    nextSceneId: "scene-106",
    nextSceneTransition: {
      preset: "fade-black",
      durationMs: 420,
    },
  },
  "scene-106": {
    id: "scene-106",
    chapterId: "ch02",
    sceneLabel: "街道",
    backgroundImage: "/images/428出圖/背景/家門口巷弄_夜晚.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "到家了，來好好想想。",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
    nextSceneId: "scene-night-hub",
    nextSceneTransition: {
      preset: "fade-black",
      durationMs: 420,
    },
  },
  "scene-night-hub": {
    id: "scene-night-hub",
    chapterId: "ch02",
    sceneLabel: "晚上客廳",
    backgroundImage: "/images/428出圖/背景/客廳_晚上.jpg",
    backgroundColor: "#3D3D45",
    characterName: "小麥",
    dialogue: "打開日記本來看看",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 8,
    dialogAvatarSpriteId: "mai",
  },
  "scene-morning-hub": {
    id: "scene-morning-hub",
    chapterId: "ch02",
    sceneLabel: "早晨",
    backgroundImage: "/images/428出圖/背景/房間_開燈.jpg",
    backgroundColor: "#CFC7A9",
    characterName: "小麥",
    dialogue: "時間差不多了",
    showDialogAvatar: true,
    dialogAvatarFrameIndex: 0,
    dialogAvatarSpriteId: "mai",
  },
  "scene-offwork": {
    id: "scene-offwork",
    chapterId: "ch02",
    sceneLabel: "下班",
    backgroundImage: "/images/428出圖/背景/公司_黃昏.jpg",
    backgroundColor: "#8E8E8E",
    characterName: "小麥",
    dialogue: "",
    showDialogueUI: false,
  },
};

export const SCENE_ORDER = [
  "scene-1",
  "scene-1a",
  "scene-2",
  "scene-2a",
  "scene-3",
  "scene-4",
  "scene-4d",
  "scene-5",
  "scene-6",
  "scene-7",
  "scene-8",
  "scene-8a",
  "scene-9",
  "scene-10",
  "scene-10a",
  "scene-10b",
  "scene-11",
  "scene-12",
  "scene-13",
  "scene-13a",
  "scene-13b",
  "scene-14",
  "scene-15",
  "scene-16",
  "scene-18",
  "scene-19",
  "scene-20",
  "scene-21",
  "scene-21a0",
  "scene-21a",
  "scene-21a2",
  "scene-21b",
  "scene-21c",
  "scene-21d",
  "scene-21f",
  "scene-21f2",
  "scene-21f3",
  "scene-21h",
  "scene-21h2",
  "scene-21-work",
  "scene-22",
  "scene-22a",
  "scene-22b",
  "scene-22c",
  "scene-22d",
  "scene-23",
  "scene-23a",
  "scene-23b",
  "scene-23c",
  "scene-23d",
  "scene-23e",
  "scene-26",
  "scene-27",
  "scene-28",
  "scene-28a",
  "scene-29",
  "scene-29a",
  "scene-29b",
  "scene-29c",
  "scene-29d",
  "scene-30",
  "scene-31",
  "scene-31a",
  "scene-31b",
  "scene-31c",
  "scene-31d",
  "scene-31e",
  "scene-31f",
  "scene-31g",
  "scene-31h",
  "scene-32",
  "scene-33",
  "scene-34",
  "scene-34a",
  "scene-35",
  "scene-36",
  "scene-37",
  "scene-38",
  "scene-39",
  "scene-39a",
  "scene-40",
  "scene-41",
  "scene-42",
  "scene-43",
  "scene-44",
  "scene-45",
  "scene-45b",
  "scene-45a",
  "scene-46",
  "scene-46a",
  "scene-47",
  "scene-48",
  "scene-48a",
  "scene-48b",
  "scene-48c",
  "scene-48d",
  "scene-48e",
  "scene-48f",
  "scene-49",
  "scene-49a",
  "scene-49b",
  "scene-49c",
  "scene-50",
  "scene-51",
  "scene-52",
  "scene-53",
  "scene-53-call",
  "scene-53b",
  "scene-54",
  "scene-54a",
  "scene-54b",
  "scene-54c",
  "scene-54d",
  "scene-54e",
  "scene-55",
  "scene-56",
  "scene-56-thought",
  "scene-56a",
  "scene-57",
  "scene-58a",
  "scene-59",
  "scene-59a",
  "scene-59b",
  "scene-59c",
  "scene-59d",
  "scene-59e",
  "scene-60",
  "scene-60a",
  "scene-60b",
  "scene-60c",
  "scene-60d",
  "scene-60e",
  "scene-60f",
  "scene-60g",
  "scene-60h",
  "scene-60i",
  "scene-60j",
  "scene-60k",
  "scene-60l",
  "scene-61",
  "scene-62",
  "scene-63",
  "scene-64",
  "scene-64a",
  "scene-64b",
  "scene-65",
  "scene-66",
  "scene-66a",
  "scene-66b",
  "scene-66c",
  "scene-66d",
  "scene-66e",
  "scene-66f",
  "scene-67",
  "scene-68",
  "scene-68a",
  "scene-69",
  "scene-70",
  "scene-71",
  "scene-72",
  "scene-73",
  "scene-73a",
  "scene-73b",
  "scene-74",
  "scene-74a",
  "scene-75",
  "scene-76",
  "scene-77",
  "scene-78",
  "scene-78a",
  "scene-78b",
  "scene-79",
  "scene-80",
  "scene-81",
  "scene-82",
  "scene-83",
  "scene-84",
  "scene-85",
  "scene-86",
  "scene-87",
  "scene-88",
  "scene-89",
  "scene-90",
  "scene-90a",
  "scene-91",
  "scene-91a",
  "scene-92",
  "scene-92a",
  "scene-93",
  "scene-94",
  "scene-95",
  "scene-95a",
  "scene-96",
  "scene-96a",
  "scene-96b",
  "scene-97",
  "scene-98",
  "scene-98-work",
  "scene-99",
  "scene-100",
  "scene-101",
  "scene-102",
  "scene-103",
  "scene-105",
  "scene-106",
  "scene-night-hub",
  "scene-morning-hub",
  "scene-offwork",
] as const;

export function getScenesByChapter(chapterId: string): GameScene[] {
  return SCENE_ORDER.map((id) => GAME_SCENES[id]).filter((scene) => scene.chapterId === chapterId);
}

export function getChapterScenesUntilScene(scene: GameScene): GameScene[] {
  const chapterScenes = getScenesByChapter(scene.chapterId);
  const currentIndex = chapterScenes.findIndex((item) => item.id === scene.id);
  if (currentIndex < 0) return [];
  return chapterScenes.slice(0, currentIndex + 1);
}

export const FIRST_SCENE_ID = "scene-1";
export const OFFWORK_SCENE_ID = "scene-offwork";
export const AFTER_REWARD_SCENE_ID = "scene-99";
