export const ROUTES = {
  home: "/",
  hibimon: "/hibimon",
  gameArrangeRoute: "/game/arrange-route",
  gameDaily: "/game/daily",
  gameDailyPrepare: "/game/daily/prepare",
  gameDailyStages: "/game/daily/stages",
  gameDailyPlay: "/game/daily/play",
  gameDailyResult: "/game/daily/result",
  gameDailyCollection: "/game/daily/collection",
  gameLobby: "/game/lobby",
  gameRoot: "/game",
  gameMap: "/game/map",
  gameScene: (sceneId: string) => `/game/${sceneId}`,
} as const;
