export const ROUTES = {
  home: "/",
  hibimon: "/hibimon",
  gameArrangeRoute: "/game/arrange-route",
  gameDaily: "/game/daily",
  gameDailyPrepare: "/game/daily/prepare",
  gameDailyStages: "/game/daily/stages",
  gameDailyPlay: "/game/daily/play",
  gameDailyResult: "/game/daily/result",
  gameDailyCollection: "/game/daily/collection",
  gameLobby: "/game/lobby",
  gameExhibition: "/game/exhibition",
  gameMarketing: "/game/marketing",
  gameMarketingSocialSummerCommute: "/game/marketing/social/summer-commute",
  gameMarketingSocialPrizeReveal: "/game/marketing/social/prize-reveal",
  gameMarketingSocialFrogRaffle: "/game/marketing/social/frog-raffle",
  gameMarketingDiaryThread: "/game/marketing/thread/diary",
  gameRoot: "/game",
  gameMap: "/game/map",
  gameScene: (sceneId: string) => `/game/${sceneId}`,
} as const;
